version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bed-dialoq-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bed_dialoq
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bed-dialoq-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:6.2
    container_name: bed-dialoq-redis
    ports:
      - "6379:6379"
    networks:
      - bed-dialoq-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bed-dialoq-app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bed_dialoq?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
    networks:
      - bed-dialoq-network

volumes:
  mysql_data:

networks:
  bed-dialoq-network: